import "./globals.css";
import localFont from "next/font/local";
import LenisRoot from "./lenis-root";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montalban = localFont({
  src: [
    { path: "../../public/font/Montalban-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../public/font/Montalban-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-montalban",
  display: "swap",
});

const artine = localFont({
  src: [
    { path: "../../public/font/Artine-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../public/font/Artine-Light.ttf", weight: "300", style: "normal" },
    { path: "../../public/font/Artine-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-artine",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${artine.className} ${montalban.variable} ${artine.variable}`}>
        <LenisRoot>
          <Header />
          {children}
          <Footer />
        </LenisRoot>
      </body>
    </html>
  );
}
